# To learn about this file, please see https://www.gitpod.io/docs/references/gitpod-yml

image: gitpod/workspace-postgres

tasks:
  - init: |
      rm ./renovate.json
      yarn install
    # Using Gitpod Local Companion? Change this to just `yarn rw dev`
    # command: yarn rw dev --fwd="--client-web-socket-url=ws$(gp url 8910 | cut -c 5-)/ws"
    command: yarn rw dev

ports:
  - port: 5432
    name: PostgreSQL database
    onOpen: ignore
  - port: 8910
    name: RedoodJS web application
    onOpen: open-browser
  - port: 8911
    name: Serverless functions
    onOpen: ignore

vscode:
  extensions:
    - "dbaeumer.vscode-eslint"
    - "eamodio.gitlens"
    - "ofhumanbondage.react-proptypes-intellisense"
    - "mgmcdermott.vscode-language-babel"
    - "wix.vscode-import-cost"
    - "pflannery.vscode-versionlens"
    - "editorconfig.editorconfig"
    - "prisma.prisma"
    - "graphql.vscode-graphql"
